@extends('layouts.admin')

@section('title', 'Work Orders')

@section('content')
<div class="bg-white rounded-lg shadow-sm">
    <div class="p-6">

        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-300">
                <thead>
                    <tr class="bg-gray-100">
                        <th class="px-4 py-2 border">ID</th>
                        <th class="px-4 py-2 border">Title</th>
                        <th class="px-4 py-2 border">Assigned To</th>
                        <th class="px-4 py-2 border">Generated By</th>
                        <th class="px-4 py-2 border">Source Request</th>
                        <th class="px-4 py-2 border">Description</th>
                        <th class="px-4 py-2 border">Status</th>
                        <th class="px-4 py-2 border">Priority</th>
                        <th class="px-4 py-2 border">Created At</th>
                        <th class="px-4 py-2 border">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($workOrders as $workOrder)
                        <tr class="hover:bg-gray-50">
                            <td class="px-4 py-2 border">{{ $workOrder->id }}</td>
                            <td class="px-4 py-2 border">{{ $workOrder->title }}</td>
                            <td class="px-4 py-2 border">{{ $workOrder->assignedToUser->name ?? 'N/A' }}</td>
                            <td class="px-4 py-2 border">{{ $workOrder->generatedByUser->name ?? 'N/A' }}</td>
                            <td class="px-4 py-2 border">
                                @if($workOrder->sourceRequest)
                                    #{{ $workOrder->sourceRequest->id }} - {{ $workOrder->sourceRequest->location->name ?? 'N/A' }}
                                @else
                                    N/A
                                @endif
                            </td>
                            <td class="px-4 py-2 border">{{ Str::limit($workOrder->description, 50) }}</td>
                            <td class="px-4 py-2 border">
                                <span class="px-2 py-1 text-xs rounded-full
                                    @if($workOrder->status === 'pending') bg-yellow-100 text-yellow-800
                                    @elseif($workOrder->status === 'completed') bg-green-100 text-green-800
                                    @else bg-gray-100 text-gray-800 @endif">
                                    {{ ucfirst($workOrder->status) }}
                                </span>
                            </td>
                            <td class="px-4 py-2 border">
                                <span class="px-2 py-1 text-xs rounded-full
                                    @if($workOrder->priority === 'low') bg-green-100 text-green-800
                                    @elseif($workOrder->priority === 'medium') bg-yellow-100 text-yellow-800
                                    @elseif($workOrder->priority === 'high') bg-orange-100 text-orange-800
                                    @else bg-red-100 text-red-800 @endif">
                                    {{ ucfirst($workOrder->priority) }}
                                </span>
                            </td>
                            <td class="px-4 py-2 border">{{ $workOrder->created_at->format('M d, Y H:i') }}</td>
                            <td class="px-4 py-2 border">
                                @if($workOrder->status !== 'completed')
                                    <form action="{{ route('admin.complete-work-order', $workOrder->id) }}" method="POST" class="inline">
                                        @csrf
                                        <button type="submit" class="px-3 py-1 text-sm font-bold text-white bg-green-500 rounded hover:bg-green-700">
                                            Complete
                                        </button>
                                    </form>
                                @else
                                    <span class="text-sm text-gray-500">
                                        Completed {{ $workOrder->completed_at ? $workOrder->completed_at->format('M d, Y') : '' }}
                                    </span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        @if($workOrders->isEmpty())
            <p class="mt-4 text-gray-500">No work orders found.</p>
        @endif
    </div>
</div>
@endsection
