<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Work Order Receipt</title>
</head>
<body>
    <div class="mb-5 no-print">
        <button class="bg-blue-600 hover:bg-blue-700 text-white border-none px-5 py-2.5 text-base cursor-pointer mb-5" onclick="window.print()">Print Receipt</button>
        <a href="{{ route('dashboard') }}" class="bg-gray-600 hover:bg-gray-700 text-white border-none px-5 py-2.5 text-base cursor-pointer no-underline ml-2.5">Back to Dashboard</a>
    </div>

    <div class="receipt">
        <div class="header">
            <h1>Work Order Receipt</h1>
            <p>School Maintenance Management System</p>
            <p>Generated on: {{ now()->format('M d, Y H:i') }}</p>
        </div>

        <div class="section">
            <h2>Work Order Details</h2>
            <div class="field">
                <label>Work Order ID:</label>
                <span>{{ $workOrder->id }}</span>
            </div>
            <div class="field">
                <label>Title:</label>
                <span>{{ $workOrder->title }}</span>
            </div>
            <div class="field">
                <label>Status:</label>
                <span>{{ ucfirst($workOrder->status) }}</span>
            </div>
            <div class="field">
                <label>Priority:</label>
                <span>{{ ucfirst($workOrder->priority) }}</span>
            </div>
            <div class="field">
                <label>Created Date:</label>
                <span>{{ $workOrder->created_at->format('M d, Y H:i') }}</span>
            </div>
        </div>

        <div class="section">
            <h2>Request Information</h2>
            <div class="field">
                <label>Original Request ID:</label>
                <span>{{ $workOrder->sourceRequest->id }}</span>
            </div>
            <div class="field">
                <label>Location:</label>
                <span>{{ $workOrder->sourceRequest->location->name ?? 'N/A' }}</span>
            </div>
            <div class="field">
                <label>Submitted By:</label>
                <span>{{ $workOrder->sourceRequest->submittedByUser->name ?? 'N/A' }}</span>
            </div>
            <div class="field">
                <label>Description:</label>
                <span>{{ $workOrder->sourceRequest->description }}</span>
            </div>
        </div>

        <div class="section">
            <h2>Assignment Details</h2>
            <div class="field">
                <label>Assigned To:</label>
                <span>{{ $workOrder->assignedToUser->name ?? 'N/A' }}</span>
            </div>
            <div class="field">
                <label>Generated By:</label>
                <span>{{ $workOrder->generatedByUser->name ?? 'N/A' }}</span>
            </div>
        </div>

        <div class="footer">
            <p>This is an official work order receipt. Please keep for your records.</p>
            <p>Thank you for using the School Maintenance Management System.</p>
        </div>
    </div>
</body>
</html>
